---
- name: install pip module
  become: yes
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: install pip module for python3
  ansible.builtin.pip:
    name: pip
    executable: pip3
    
- name: pip install python k8s lib
  ansible.builtin.pip:
    name: kubernetes
